// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alaigo.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	alaigo.proto

It has these top-level messages:
	User
	SearchRequest
	SearchResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	TelephoneNumber string `protobuf:"bytes,1,opt,name=telephone_number,json=telephoneNumber" json:"telephone_number,omitempty"`
	UserName        string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	UserPassword    string `protobuf:"bytes,3,opt,name=user_password,json=userPassword" json:"user_password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetTelephoneNumber() string {
	if m != nil {
		return m.TelephoneNumber
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetUserPassword() string {
	if m != nil {
		return m.UserPassword
	}
	return ""
}

type SearchRequest struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	User      *User  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SearchRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchResponse struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SearchResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto1.RegisterType((*User)(nil), "proto.User")
	proto1.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto1.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SearchService service

type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/proto.SearchService/search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alaigo.proto",
}

func init() { proto1.RegisterFile("alaigo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x94, 0x42, 0xae, 0x2d, 0x20, 0x0b, 0xa4, 0x08, 0x84, 0x40, 0x61, 0x81, 0xa5,
	0x43, 0x19, 0xd8, 0x99, 0xe8, 0x52, 0x50, 0x2a, 0xe6, 0xc8, 0x4d, 0x4e, 0x34, 0x52, 0x63, 0x87,
	0x3b, 0x07, 0x56, 0x46, 0x46, 0x7e, 0x32, 0xca, 0xc5, 0x41, 0x82, 0x85, 0xc9, 0xf6, 0x77, 0xcf,
	0xf7, 0xde, 0x83, 0xb1, 0xd9, 0x98, 0xf2, 0xc5, 0x4d, 0x6b, 0x72, 0xde, 0xe9, 0x5d, 0x39, 0x12,
	0x86, 0xc1, 0x33, 0x23, 0xe9, 0x1b, 0x38, 0xf2, 0xb8, 0xc1, 0x7a, 0xed, 0x2c, 0x66, 0xb6, 0xa9,
	0x56, 0x48, 0xb1, 0xba, 0x54, 0xd7, 0x51, 0x7a, 0xf8, 0xc3, 0x17, 0x82, 0xf5, 0x19, 0x44, 0x0d,
	0x23, 0x65, 0xd6, 0x54, 0x18, 0x6f, 0x8b, 0x66, 0xbf, 0x05, 0x0b, 0x53, 0xa1, 0xbe, 0x82, 0x89,
	0x0c, 0x6b, 0xc3, 0xfc, 0xee, 0xa8, 0x88, 0x77, 0x44, 0x30, 0x6e, 0xe1, 0x53, 0x60, 0xc9, 0x23,
	0x4c, 0x96, 0x68, 0x28, 0x5f, 0xa7, 0xf8, 0xda, 0x20, 0x7b, 0x7d, 0x0e, 0x40, 0xdd, 0x35, 0x2b,
	0x8b, 0xe0, 0x1b, 0x05, 0x32, 0x2f, 0xf4, 0x05, 0x0c, 0xda, 0xff, 0x62, 0x36, 0x9a, 0x8d, 0xba,
	0x06, 0xd3, 0x36, 0x77, 0x2a, 0x83, 0x64, 0x0e, 0x07, 0xfd, 0x42, 0xae, 0x9d, 0x65, 0xfc, 0x6f,
	0x63, 0x0c, 0x7b, 0xb9, 0xb3, 0x1e, 0xad, 0x0f, 0x0d, 0xfa, 0xe7, 0xec, 0xa1, 0xcf, 0xb6, 0x44,
	0x7a, 0x2b, 0x73, 0xd4, 0x77, 0x30, 0x64, 0x01, 0xfa, 0x38, 0x18, 0xff, 0xca, 0x7e, 0x7a, 0xf2,
	0x87, 0x76, 0x01, 0x92, 0xad, 0xfb, 0xe8, 0x43, 0xa9, 0x4f, 0xa5, 0xbe, 0x94, 0x5a, 0x0d, 0x45,
	0x72, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xfb, 0x3d, 0xc0, 0x83, 0x01, 0x00, 0x00,
}
